import 'package:flutter/material.dart';
import 'package:flutterapp/final_app/generatedhorariosdecomidawidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/final_app/generatedhorariosdecomidawidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/final_app/generatedhorariosdecomidawidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/final_app/generatedhorariosdecomidawidget/generated/GeneratedNavegadorWidget2.dart';
import 'package:flutterapp/final_app/generatedhorariosdecomidawidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/final_app/generatedhorariosdecomidawidget/generated/GeneratedHorariosdecomidaparalosreosWidget.dart';

/* Frame Horarios de comida
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHorariosdecomidaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 419.0,
                height: 86.0,
                child: GeneratedNavegadorWidget2(),
              ),
              Positioned(
                left: 23.0,
                top: 18.0,
                right: null,
                bottom: null,
                width: 353.0,
                height: 71.0,
                child: GeneratedHorariosdecomidaparalosreosWidget(),
              ),
              Positioned(
                left: 198.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 248.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 125.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 125.0,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 256.4079895019531,
                child: GeneratedGroup6Widget(),
              )
            ]),
      ),
    ));
  }
}
