import 'package:flutter/material.dart';
import 'package:flutterapp/final_app/generatedmapadelacarcelwidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/final_app/generatedmapadelacarcelwidget/generated/GeneratedNavegadorWidget.dart';
import 'package:flutterapp/final_app/generatedmapadelacarcelwidget/generated/GeneratedMAPADELACARCELWidget.dart';

/* Frame Mapa de la carcel
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMapadelacarcelWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 419.0,
                height: 86.0,
                child: GeneratedNavegadorWidget(),
              ),
              Positioned(
                left: 72.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 48.0,
                child: GeneratedMAPADELACARCELWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 433.0,
                child: GeneratedRectangle7Widget(),
              )
            ]),
      ),
    ));
  }
}
