import 'package:flutter/material.dart';
import 'package:flutterapp/final_app/generatedguardiainiciodesesionwidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/final_app/generatedguardiainiciodesesionwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/final_app/generatedguardiainiciodesesionwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/final_app/generatedguardiainiciodesesionwidget/generated/GeneratedCeresodemaximaseguridadWidget.dart';
import 'package:flutterapp/final_app/generatedguardiainiciodesesionwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/final_app/generatedguardiainiciodesesionwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/final_app/generatedguardiainiciodesesionwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/final_app/generatedguardiainiciodesesionwidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/final_app/generatedguardiainiciodesesionwidget/generated/GeneratedGuardiadeseguridadWidget.dart';

/* Frame Guardia inicio de sesion
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGuardiainiciodesesionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 570.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 570.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 390.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 74.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 41.0,
                child: GeneratedGuardiadeseguridadWidget(),
              ),
              Positioned(
                left: 81.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 24.0,
                child: GeneratedCeresodemaximaseguridadWidget(),
              ),
              Positioned(
                left: 132.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 1.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: -6.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 366.0,
                height: 73.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 674.0,
                right: null,
                bottom: null,
                width: 366.0,
                height: 73.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 120.0,
                top: 778.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 41.0,
                child: GeneratedGroup3Widget(),
              )
            ]),
      ),
    ));
  }
}
