import 'package:flutter/material.dart';
import 'package:flutterapp/final_app/generatedreoswidget3/generated/GeneratedDatosdereosWidget2.dart';
import 'package:flutterapp/final_app/generatedreoswidget3/generated/GeneratedDatosdereosWidget1.dart';
import 'package:flutterapp/final_app/generatedreoswidget3/generated/GeneratedDatosdereosWidget.dart';
import 'package:flutterapp/final_app/generatedreoswidget3/generated/GeneratedDatosdereosWidget3.dart';
import 'package:flutterapp/final_app/generatedreoswidget3/generated/GeneratedNavegadorWidget3.dart';

/* Frame Reos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReosWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 419.0,
                height: 86.0,
                child: GeneratedNavegadorWidget3(),
              ),
              Positioned(
                left: 14.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 161.0,
                child: GeneratedDatosdereosWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 161.0,
                child: GeneratedDatosdereosWidget1(),
              ),
              Positioned(
                left: 14.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 161.0,
                child: GeneratedDatosdereosWidget2(),
              ),
              Positioned(
                left: 14.0,
                top: 616.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 161.0,
                child: GeneratedDatosdereosWidget3(),
              )
            ]),
      ),
    ));
  }
}
