import 'package:flutter/material.dart';
import 'package:flutterapp/final_app/generateddatosdereoswidget4/generated/GeneratedNombreWidget5.dart';
import 'package:flutterapp/final_app/generateddatosdereoswidget4/generated/GeneratedRoboyasaltoWidget4.dart';
import 'package:flutterapp/final_app/generateddatosdereoswidget4/generated/GeneratedCasoWidget4.dart';
import 'package:flutterapp/final_app/generateddatosdereoswidget4/generated/GeneratedRectangle10Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/final_app/generateddatosdereoswidget4/generated/GeneratedREOWidget4.dart';
import 'package:flutterapp/final_app/generateddatosdereoswidget4/generated/GeneratedLuisLopezCordobaWidget4.dart';
import 'package:flutterapp/final_app/generateddatosdereoswidget4/generated/GeneratedEllipse1Widget4.dart';

/* Component Datos de reos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDatosdereosWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 383.0,
      height: 161.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle10Widget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.29765013054830286;
                double scaleX = (constraints.maxWidth * percentWidth) / 114.0;

                double percentHeight = 0.7142857142857143;
                double scaleY = (constraints.maxHeight * percentHeight) / 115.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.028720626631853787,
                      translateY: constraints.maxHeight * 0.14285714285714285,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedEllipse1Widget4())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.195822454308094;

                final double height = constraints.maxHeight * 0.422360248447205;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.1122715404699739,
                      y: constraints.maxHeight * 0.391304347826087,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedREOWidget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.5509138381201044;

                final double height =
                    constraints.maxHeight * 0.19875776397515527;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.3577023498694517,
                      y: constraints.maxHeight * 0.14285714285714285,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedNombreWidget5(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.5430809399477807;

                final double height =
                    constraints.maxHeight * 0.18012422360248448;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.3577023498694517,
                      y: constraints.maxHeight * 0.30434782608695654,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedLuisLopezCordobaWidget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.5509138381201044;

                final double height =
                    constraints.maxHeight * 0.19875776397515527;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.3577023498694517,
                      y: constraints.maxHeight * 0.5031055900621118,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedCasoWidget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.5430809399477807;

                final double height =
                    constraints.maxHeight * 0.18012422360248448;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.3577023498694517,
                      y: constraints.maxHeight * 0.6708074534161491,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRoboyasaltoWidget4(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
