import 'package:flutter/material.dart';
import 'package:flutterapp/final_app/generatedhorariosactividadeswidget/generated/GeneratedNavegadorWidget4.dart';
import 'package:flutterapp/final_app/generatedhorariosactividadeswidget/generated/GeneratedHORARIODEACTIVIDADESESCOLARESPARALOSREOSWidget.dart';
import 'package:flutterapp/final_app/generatedhorariosactividadeswidget/generated/GeneratedRectangle11Widget.dart';

/* Frame Horarios actividades
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHorariosactividadesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 419.0,
                height: 86.0,
                child: GeneratedNavegadorWidget4(),
              ),
              Positioned(
                left: 47.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 537.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 93.0,
                child:
                    GeneratedHORARIODEACTIVIDADESESCOLARESPARALOSREOSWidget(),
              )
            ]),
      ),
    ));
  }
}
